"use client"
// components/shared/ReferralCapture.tsx
// Mounted once in the root layout. Fixes referral links not working when
// shared with someone who isn't registered yet:
//   - The link generated by ReferralsService.getReferralLink() is just
//     "https://zamorax.ng?ref=<uid>" (the homepage), not "/register?ref=...".
//     A logged-out visitor landing there with ?ref= present was getting
//     nothing — the homepage never read that param.
//   - This component reads ?ref= on ANY page, persists it to localStorage so
//     it survives if the person browses around before signing up, and — if
//     they're not logged in — sends them straight to /register?ref=... so
//     the code is pre-filled and applied automatically.
//   - RegisterForm already reads ?ref= from the URL; it now also falls back
//     to the stashed localStorage value if the query param is missing
//     (e.g. they clicked "Register" from the navbar after landing here).

import { useEffect } from "react"
import { useRouter, usePathname, useSearchParams } from "next/navigation"
import { useAuthStore } from "@/store/authStore"

export const REFERRAL_STORAGE_KEY = "zamorax_referral_code"

// Pages where we should NOT auto-redirect even if ?ref= is present —
// register/login already handle it themselves, and we don't want to hijack
// checkout or other flows that might legitimately carry a ref param through.
const SKIP_REDIRECT_PATHS = ["/register", "/login", "/become-seller"]

export function ReferralCapture() {
  const router = useRouter()
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const { user, loading } = useAuthStore()

  useEffect(() => {
    const ref = searchParams.get("ref")
    if (!ref) return

    try {
      localStorage.setItem(REFERRAL_STORAGE_KEY, ref)
    } catch { /* localStorage unavailable — non-fatal, redirect still works */ }

    // Wait for the auth check to resolve so we don't redirect someone who's
    // actually already logged in (they don't need to register).
    if (loading) return
    if (user) return
    if (SKIP_REDIRECT_PATHS.some(p => pathname?.startsWith(p))) return

    router.replace(`/register?ref=${encodeURIComponent(ref)}`)
  }, [searchParams, pathname, user, loading, router])

  return null
}
